import React from 'react';
import { useStore } from '../../context/StoreContext';
import { ArrowDown, Play, Disc } from 'lucide-react';

export const HeroSection: React.FC = () => {
  const { setCurrentScene, setCursorText } = useStore();

  return (
    <section
      id="hero"
      className="min-h-screen w-full flex flex-col justify-center items-center py-20 px-4 sm:px-8 max-w-5xl mx-auto z-10 select-none text-center relative"
    >
      {/* Top Academic Tag */}
      <div className="flex flex-col sm:flex-row items-center justify-center gap-2 mb-8">
        <div className="inline-flex items-center space-x-2 px-3 py-1 bg-white/5 border border-white/10 rounded-full">
          <span className="w-2 h-2 rounded-full bg-white animate-pulse" />
          <span className="font-mono text-[10px] sm:text-[11px] tracking-[0.2em] uppercase text-neutral-300">
            BS Computer Science Thesis · University of Southeastern Philippines
          </span>
        </div>
      </div>

      {/* Main Headline */}
      <div className="flex flex-col items-center max-w-4xl mx-auto mb-8">
        <div className="text-[11px] font-mono tracking-[0.25em] uppercase text-neutral-400 mb-4 flex items-center justify-center gap-2">
          <Disc className="w-3.5 h-3.5 animate-spin text-neutral-300" />
          <span>AI-GENERATED MUSIC DETECTION SYSTEM</span>
        </div>

        <h1 className="text-5xl sm:text-7xl md:text-8xl font-display font-medium tracking-tighter leading-[0.95] text-white">
          Is this song <br />
          <span className="italic font-light text-neutral-300">human?</span>
        </h1>

        <p className="mt-6 text-base sm:text-xl text-neutral-300 font-normal max-w-2xl leading-relaxed tracking-tight mx-auto">
          Know-Ta! listens to the singer's voice and the background music{' '}
          <span className="text-white font-medium border-b border-white/40">separately</span>,{' '}
          making it simple and accurate to tell if a track was generated by AI.
        </p>

        {/* Action Buttons - Centered */}
        <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
          <button
            onClick={() => setCurrentScene('demo')}
            onMouseEnter={() => setCursorText('DEMO')}
            onMouseLeave={() => setCursorText('')}
            className="group relative inline-flex items-center space-x-2.5 px-6 py-3 bg-white text-black font-mono text-xs tracking-widest uppercase font-semibold hover:bg-neutral-200 transition-all duration-200 active:scale-95 rounded"
          >
            <Play className="w-3.5 h-3.5 fill-black" />
            <span>Test a Song (Try Demo)</span>
            <span className="text-[10px] opacity-60">→</span>
          </button>

          <button
            onClick={() => setCurrentScene('problem')}
            onMouseEnter={() => setCursorText('EXPLORE')}
            onMouseLeave={() => setCursorText('')}
            className="inline-flex items-center space-x-2.5 px-5 py-3 border border-white/20 text-neutral-200 font-mono text-xs tracking-widest uppercase font-normal hover:bg-white/5 hover:border-white transition-all duration-200 rounded"
          >
            <span>How It Works</span>
            <ArrowDown className="w-3 h-3 text-neutral-400" />
          </button>

          <button
            onClick={() => setCurrentScene('research')}
            onMouseEnter={() => setCursorText('THESIS')}
            onMouseLeave={() => setCursorText('')}
            className="inline-flex items-center space-x-1.5 px-4 py-3 text-neutral-400 hover:text-white font-mono text-xs tracking-wider uppercase transition-colors"
          >
            <span>Thesis Details</span>
            <span className="text-[10px] text-neutral-500">↗</span>
          </button>
        </div>
      </div>

      {/* Real Empirical Stat Strip in Clear Everyday Language */}
      <div className="w-full border-t border-b border-white/10 py-5 my-6">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-center">
          <div className="space-y-1">
            <div className="font-display text-2xl sm:text-3xl font-medium tracking-tight text-white">
              97%
            </div>
            <div className="text-xs sm:text-sm text-neutral-300 font-medium">
              Of listeners can't tell AI music from real music by ear
            </div>
            <div className="text-[9px] font-mono text-neutral-500 uppercase tracking-wider">
              Deezer / Ipsos 9,000-Person Blind Test
            </div>
          </div>

          <div className="space-y-1">
            <div className="font-display text-2xl sm:text-3xl font-medium tracking-tight text-white">
              ~90,000
            </div>
            <div className="text-xs sm:text-sm text-neutral-300 font-medium">
              Fully AI songs uploaded every single day
            </div>
            <div className="text-[9px] font-mono text-neutral-500 uppercase tracking-wider">
              Streaming Catalog Reports
            </div>
          </div>

          <div className="space-y-1">
            <div className="font-display text-2xl sm:text-3xl font-medium tracking-tight text-white">
              24%
            </div>
            <div className="text-xs sm:text-sm text-neutral-300 font-medium">
              Of musician revenues at risk from AI tools
            </div>
            <div className="text-[9px] font-mono text-neutral-500 uppercase tracking-wider">
              Creator Impact Study
            </div>
          </div>
        </div>
      </div>

      {/* Thesis Dedication */}
      <div className="text-center pt-2">
        <p className="font-mono text-[10px] tracking-wider text-neutral-400 uppercase">
          In Partial Fulfillment of the Requirements for the Degree Bachelor of Science in Computer Science
        </p>
        <p className="font-mono text-[10px] text-neutral-500 mt-1">
          Kent Paulo R. Delgado · Earl Josh B. Delgado · John Renan N. Labay
        </p>
      </div>
    </section>
  );
};
